spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-pdopkmq0.cd.tencentcdb.com:10134/office_system?serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: abcd1234
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    #host: smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: project.system.domain
tx:
  cos:
    secretId: AKIDe5sQpzRXu3zf44hQp6KOnxbzDCvQbeNw
    secretKey: ub2CZgZBfusa5h7HAoa7NkXKtI8QTFnc
    region: ap-nanjing
    bucketName: officesystem-1304131169
    path: https://officesystem-1304131169.cos.ap-nanjing.myqcloud.com/
    prefix: officesystemCloudFile
aliyun:
  accessKeyID: LTAI4G36y3VKJyASeRWUNScU
  accessKeySecret: vgX0Ow3E2gyjN1A1C6yfc7w3B1ZShQ
  domain: dysmsapi.aliyuncs.com
  regionId: cn-beijing
  templateCode: SMS_206545859
  signName: JavaEEPro
  smsEffectiveTime: 2

config:
  jwt:
    # 加密密钥
    secret: iwqjhda8232bjgh432[cicada-smile]
    # token有效时长
    expire: 3600
    # header 名称
    header: Authorization
    #prefix 前缀
    prefix: Bearer
    #iss 签发者
    iss: miaowhu
server:
  port: 9000
