spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-9i2suojo.cd.tencentcdb.com:10192/officesystem?serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: lxp123456
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    #host: smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: project.system.domain
tx:
  cos:
    secretId: AKIDe5sQpzRXu3zf44hQp6KOnxbzDCvQbeNw
    secretKey: ub2CZgZBfusa5h7HAoa7NkXKtI8QTFnc
    region: ap-nanjing
    bucketName: officesystem-1304131169
    path: https://officesystem-1304131169.cos.ap-nanjing.myqcloud.com/
    prefix: officesystemCloudFile
#  speech:
#    secretId: AKIDWmAJBdFR0LrfkUzGVWIrBD0bNvBCbXnk
#    secretKey: t4xYw5yadWZN0xe6GE0tWt0FFySpKYVC
aliyun:
  accessKeyID: LTAI4G4F1c1cBGeJis39KE3i
  accessKeySecret: aOxIV5RtrJRk9aCP2yDUbrYhwHzDxi
  domain: dysmsapi.aliyuncs.com
  regionId: ap-nanjing
  templateCode: SMS_205445358
  signName: JavaEEPro
  smsEffectiveTime: 2
server:
  port: 9000
openvidu:
  #  url: https://212.64.65.145:4443/
  url: https://sx3.51guagua.top
  secret: wangxiaowei
